### ISSUE TITLE
block imageLocation description issue

### ISSUE THREAD

**Issue by heqichen** [taweili/openblocks#3]
change imageLocation from absolute address to relative address in 
<BlockGenus>
    ...
    <Images>
        <Image>
            <FileLocation>here</FileLocation>
        </Image>
    </Images>
</BlockGenus>

**Comment by taweili** [comment]
Fixed. FileLocation can be inside the classpath and jar.

**Comment by taweili** [comment]
Sorry, just found out it was in a local branch. Update the repository...
